// Code generated by protoc-gen-go.
// source: mysqlx_expect.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Open_CtxOperation int32

const (
	// copy the operations from the parent Expect-block
	Open_EXPECT_CTX_COPY_PREV Open_CtxOperation = 0
	// start with a empty set of operations
	Open_EXPECT_CTX_EMPTY Open_CtxOperation = 1
)

var Open_CtxOperation_name = map[int32]string{
	0: "EXPECT_CTX_COPY_PREV",
	1: "EXPECT_CTX_EMPTY",
}
var Open_CtxOperation_value = map[string]int32{
	"EXPECT_CTX_COPY_PREV": 0,
	"EXPECT_CTX_EMPTY":     1,
}

func (x Open_CtxOperation) Enum() *Open_CtxOperation {
	p := new(Open_CtxOperation)
	*p = x
	return p
}
func (x Open_CtxOperation) String() string {
	return proto1.EnumName(Open_CtxOperation_name, int32(x))
}
func (x *Open_CtxOperation) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(Open_CtxOperation_value, data, "Open_CtxOperation")
	if err != nil {
		return err
	}
	*x = Open_CtxOperation(value)
	return nil
}
func (Open_CtxOperation) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 0} }

type Open_Condition_ConditionOperation int32

const (
	// set the condition
	//
	// set, if not set
	// overwrite, if set
	Open_Condition_EXPECT_OP_SET Open_Condition_ConditionOperation = 0
	// unset the condition
	Open_Condition_EXPECT_OP_UNSET Open_Condition_ConditionOperation = 1
)

var Open_Condition_ConditionOperation_name = map[int32]string{
	0: "EXPECT_OP_SET",
	1: "EXPECT_OP_UNSET",
}
var Open_Condition_ConditionOperation_value = map[string]int32{
	"EXPECT_OP_SET":   0,
	"EXPECT_OP_UNSET": 1,
}

func (x Open_Condition_ConditionOperation) Enum() *Open_Condition_ConditionOperation {
	p := new(Open_Condition_ConditionOperation)
	*p = x
	return p
}
func (x Open_Condition_ConditionOperation) String() string {
	return proto1.EnumName(Open_Condition_ConditionOperation_name, int32(x))
}
func (x *Open_Condition_ConditionOperation) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(Open_Condition_ConditionOperation_value, data, "Open_Condition_ConditionOperation")
	if err != nil {
		return err
	}
	*x = Open_Condition_ConditionOperation(value)
	return nil
}
func (Open_Condition_ConditionOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{0, 0, 0}
}

// open an Expect block and set/unset the conditions that have to be fulfilled
//
// if any of the conditions fail, all enclosed messages will fail with
// a Mysqlx.Error message.
//
// :returns: :protobuf:msg:`Mysqlx::Ok` on success, :protobuf:msg:`Mysqlx::Error` on error
//
type Open struct {
	Op               *Open_CtxOperation `protobuf:"varint,1,opt,name=op,enum=Mysqlx.Expect.Open_CtxOperation,def=0" json:"op,omitempty"`
	Cond             []*Open_Condition  `protobuf:"bytes,2,rep,name=cond" json:"cond,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Open) Reset()                    { *m = Open{} }
func (m *Open) String() string            { return proto1.CompactTextString(m) }
func (*Open) ProtoMessage()               {}
func (*Open) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

const Default_Open_Op Open_CtxOperation = Open_EXPECT_CTX_COPY_PREV

func (m *Open) GetOp() Open_CtxOperation {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return Default_Open_Op
}

func (m *Open) GetCond() []*Open_Condition {
	if m != nil {
		return m.Cond
	}
	return nil
}

type Open_Condition struct {
	ConditionKey     *uint32                            `protobuf:"varint,1,req,name=condition_key" json:"condition_key,omitempty"`
	ConditionValue   []byte                             `protobuf:"bytes,2,opt,name=condition_value" json:"condition_value,omitempty"`
	Op               *Open_Condition_ConditionOperation `protobuf:"varint,3,opt,name=op,enum=Mysqlx.Expect.Open_Condition_ConditionOperation,def=0" json:"op,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *Open_Condition) Reset()                    { *m = Open_Condition{} }
func (m *Open_Condition) String() string            { return proto1.CompactTextString(m) }
func (*Open_Condition) ProtoMessage()               {}
func (*Open_Condition) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 0} }

const Default_Open_Condition_Op Open_Condition_ConditionOperation = Open_Condition_EXPECT_OP_SET

func (m *Open_Condition) GetConditionKey() uint32 {
	if m != nil && m.ConditionKey != nil {
		return *m.ConditionKey
	}
	return 0
}

func (m *Open_Condition) GetConditionValue() []byte {
	if m != nil {
		return m.ConditionValue
	}
	return nil
}

func (m *Open_Condition) GetOp() Open_Condition_ConditionOperation {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return Default_Open_Condition_Op
}

// close a Expect block
//
// closing a Expect block restores the state of the previous Expect block
// for the following messages
//
// :returns: :protobuf:msg:`Mysqlx::Ok` on success, :protobuf:msg:`Mysqlx::Error` on error
type Close struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Close) Reset()                    { *m = Close{} }
func (m *Close) String() string            { return proto1.CompactTextString(m) }
func (*Close) ProtoMessage()               {}
func (*Close) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func init() {
	proto1.RegisterType((*Open)(nil), "Mysqlx.Expect.Open")
	proto1.RegisterType((*Open_Condition)(nil), "Mysqlx.Expect.Open.Condition")
	proto1.RegisterType((*Close)(nil), "Mysqlx.Expect.Close")
	proto1.RegisterEnum("Mysqlx.Expect.Open_CtxOperation", Open_CtxOperation_name, Open_CtxOperation_value)
	proto1.RegisterEnum("Mysqlx.Expect.Open_Condition_ConditionOperation", Open_Condition_ConditionOperation_name, Open_Condition_ConditionOperation_value)
}

func init() { proto1.RegisterFile("mysqlx_expect.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xce, 0xad, 0x2c, 0x2e,
	0xcc, 0xa9, 0x88, 0x4f, 0xad, 0x28, 0x48, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0xf5, 0x05, 0x0b, 0xea, 0xb9, 0x82, 0x05, 0x95, 0x1a, 0x98, 0xb9, 0x58, 0xfc, 0x0b, 0x52,
	0xf3, 0x84, 0x9c, 0xb8, 0x98, 0xf2, 0x0b, 0x24, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0x14, 0xf4,
	0x50, 0x14, 0xe9, 0x81, 0x14, 0xe8, 0x39, 0x97, 0x54, 0xf8, 0x17, 0xa4, 0x16, 0x25, 0x96, 0x64,
	0xe6, 0xe7, 0x59, 0x89, 0xb8, 0x46, 0x04, 0xb8, 0x3a, 0x87, 0xc4, 0x3b, 0x87, 0x44, 0xc4, 0x3b,
	0xfb, 0x07, 0x44, 0xc6, 0x07, 0x04, 0xb9, 0x86, 0x09, 0x69, 0x73, 0xb1, 0x24, 0xe7, 0xe7, 0xa5,
	0x48, 0x30, 0x29, 0x30, 0x6b, 0x70, 0x1b, 0xc9, 0x62, 0x35, 0x25, 0x3f, 0x2f, 0x25, 0x13, 0x64,
	0x84, 0xd4, 0x31, 0x46, 0x2e, 0x4e, 0x38, 0x4f, 0x48, 0x94, 0x8b, 0x37, 0x19, 0xc6, 0x89, 0xcf,
	0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd2, 0xe0, 0x15, 0x12, 0xe7, 0xe2, 0x47, 0x08, 0x97, 0x25,
	0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x08, 0x79, 0x83, 0x9d, 0xcb, 0x0c, 0x76,
	0xae, 0x01, 0x5e, 0x8b, 0x10, 0x2c, 0x84, 0xf3, 0x79, 0xa1, 0xce, 0xf7, 0x0f, 0x88, 0x0f, 0x76,
	0x0d, 0x51, 0xb2, 0xe1, 0x12, 0xc2, 0x54, 0x24, 0x24, 0xc8, 0x85, 0xaa, 0x4c, 0x80, 0x41, 0x48,
	0x98, 0x8b, 0x1f, 0x21, 0x14, 0xea, 0x07, 0x12, 0x64, 0x54, 0xb2, 0xe3, 0xe2, 0x41, 0x0e, 0x1b,
	0x21, 0x09, 0x2e, 0xac, 0xa1, 0x23, 0xc0, 0x20, 0x24, 0xc2, 0x25, 0x80, 0x24, 0xe3, 0xea, 0x1b,
	0x10, 0x12, 0x29, 0xc0, 0xa8, 0xc4, 0xce, 0xc5, 0xea, 0x9c, 0x93, 0x5f, 0x9c, 0xea, 0xa4, 0xca,
	0x25, 0x93, 0x9c, 0x9f, 0xab, 0x07, 0x8e, 0x35, 0xbd, 0xe4, 0x2c, 0x08, 0xa3, 0x02, 0x12, 0x6f,
	0x49, 0xa5, 0x69, 0x51, 0xac, 0x60, 0x16, 0x20, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x4c, 0xd0, 0xcd,
	0xd7, 0x01, 0x00, 0x00,
}
