// Code generated by protoc-gen-go.
// source: mysqlx_datatypes.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Scalar_Type int32

const (
	Scalar_V_SINT   Scalar_Type = 1
	Scalar_V_UINT   Scalar_Type = 2
	Scalar_V_NULL   Scalar_Type = 3
	Scalar_V_OCTETS Scalar_Type = 4
	Scalar_V_DOUBLE Scalar_Type = 5
	Scalar_V_FLOAT  Scalar_Type = 6
	Scalar_V_BOOL   Scalar_Type = 7
	Scalar_V_STRING Scalar_Type = 8
)

var Scalar_Type_name = map[int32]string{
	1: "V_SINT",
	2: "V_UINT",
	3: "V_NULL",
	4: "V_OCTETS",
	5: "V_DOUBLE",
	6: "V_FLOAT",
	7: "V_BOOL",
	8: "V_STRING",
}
var Scalar_Type_value = map[string]int32{
	"V_SINT":   1,
	"V_UINT":   2,
	"V_NULL":   3,
	"V_OCTETS": 4,
	"V_DOUBLE": 5,
	"V_FLOAT":  6,
	"V_BOOL":   7,
	"V_STRING": 8,
}

func (x Scalar_Type) Enum() *Scalar_Type {
	p := new(Scalar_Type)
	*p = x
	return p
}
func (x Scalar_Type) String() string {
	return proto1.EnumName(Scalar_Type_name, int32(x))
}
func (x *Scalar_Type) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(Scalar_Type_value, data, "Scalar_Type")
	if err != nil {
		return err
	}
	*x = Scalar_Type(value)
	return nil
}
func (Scalar_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 0} }

type Any_Type int32

const (
	Any_SCALAR Any_Type = 1
	Any_OBJECT Any_Type = 2
	Any_ARRAY  Any_Type = 3
)

var Any_Type_name = map[int32]string{
	1: "SCALAR",
	2: "OBJECT",
	3: "ARRAY",
}
var Any_Type_value = map[string]int32{
	"SCALAR": 1,
	"OBJECT": 2,
	"ARRAY":  3,
}

func (x Any_Type) Enum() *Any_Type {
	p := new(Any_Type)
	*p = x
	return p
}
func (x Any_Type) String() string {
	return proto1.EnumName(Any_Type_name, int32(x))
}
func (x *Any_Type) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(Any_Type_value, data, "Any_Type")
	if err != nil {
		return err
	}
	*x = Any_Type(value)
	return nil
}
func (Any_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{3, 0} }

// a scalar
type Scalar struct {
	Type         *Scalar_Type `protobuf:"varint,1,req,name=type,enum=Mysqlx.Datatypes.Scalar_Type" json:"type,omitempty"`
	VSignedInt   *int64       `protobuf:"zigzag64,2,opt,name=v_signed_int" json:"v_signed_int,omitempty"`
	VUnsignedInt *uint64      `protobuf:"varint,3,opt,name=v_unsigned_int" json:"v_unsigned_int,omitempty"`
	// 4 is unused, was Null which doesn't have a storage anymore
	VOctets          *Scalar_Octets `protobuf:"bytes,5,opt,name=v_octets" json:"v_octets,omitempty"`
	VDouble          *float64       `protobuf:"fixed64,6,opt,name=v_double" json:"v_double,omitempty"`
	VFloat           *float32       `protobuf:"fixed32,7,opt,name=v_float" json:"v_float,omitempty"`
	VBool            *bool          `protobuf:"varint,8,opt,name=v_bool" json:"v_bool,omitempty"`
	VString          *Scalar_String `protobuf:"bytes,9,opt,name=v_string" json:"v_string,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Scalar) Reset()                    { *m = Scalar{} }
func (m *Scalar) String() string            { return proto1.CompactTextString(m) }
func (*Scalar) ProtoMessage()               {}
func (*Scalar) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Scalar) GetType() Scalar_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Scalar_V_SINT
}

func (m *Scalar) GetVSignedInt() int64 {
	if m != nil && m.VSignedInt != nil {
		return *m.VSignedInt
	}
	return 0
}

func (m *Scalar) GetVUnsignedInt() uint64 {
	if m != nil && m.VUnsignedInt != nil {
		return *m.VUnsignedInt
	}
	return 0
}

func (m *Scalar) GetVOctets() *Scalar_Octets {
	if m != nil {
		return m.VOctets
	}
	return nil
}

func (m *Scalar) GetVDouble() float64 {
	if m != nil && m.VDouble != nil {
		return *m.VDouble
	}
	return 0
}

func (m *Scalar) GetVFloat() float32 {
	if m != nil && m.VFloat != nil {
		return *m.VFloat
	}
	return 0
}

func (m *Scalar) GetVBool() bool {
	if m != nil && m.VBool != nil {
		return *m.VBool
	}
	return false
}

func (m *Scalar) GetVString() *Scalar_String {
	if m != nil {
		return m.VString
	}
	return nil
}

// a string with a charset/collation
type Scalar_String struct {
	Value            []byte  `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	Collation        *uint64 `protobuf:"varint,2,opt,name=collation" json:"collation,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Scalar_String) Reset()                    { *m = Scalar_String{} }
func (m *Scalar_String) String() string            { return proto1.CompactTextString(m) }
func (*Scalar_String) ProtoMessage()               {}
func (*Scalar_String) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 0} }

func (m *Scalar_String) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Scalar_String) GetCollation() uint64 {
	if m != nil && m.Collation != nil {
		return *m.Collation
	}
	return 0
}

// an opaque octet sequence, with an optional content_type
// See ``Mysqlx.Resultset.ColumnMetadata`` for list of known values.
type Scalar_Octets struct {
	Value            []byte  `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	ContentType      *uint32 `protobuf:"varint,2,opt,name=content_type" json:"content_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Scalar_Octets) Reset()                    { *m = Scalar_Octets{} }
func (m *Scalar_Octets) String() string            { return proto1.CompactTextString(m) }
func (*Scalar_Octets) ProtoMessage()               {}
func (*Scalar_Octets) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 1} }

func (m *Scalar_Octets) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Scalar_Octets) GetContentType() uint32 {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return 0
}

// a object
type Object struct {
	Fld              []*Object_ObjectField `protobuf:"bytes,1,rep,name=fld" json:"fld,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Object) Reset()                    { *m = Object{} }
func (m *Object) String() string            { return proto1.CompactTextString(m) }
func (*Object) ProtoMessage()               {}
func (*Object) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *Object) GetFld() []*Object_ObjectField {
	if m != nil {
		return m.Fld
	}
	return nil
}

type Object_ObjectField struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *Any    `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Object_ObjectField) Reset()                    { *m = Object_ObjectField{} }
func (m *Object_ObjectField) String() string            { return proto1.CompactTextString(m) }
func (*Object_ObjectField) ProtoMessage()               {}
func (*Object_ObjectField) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1, 0} }

func (m *Object_ObjectField) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Object_ObjectField) GetValue() *Any {
	if m != nil {
		return m.Value
	}
	return nil
}

// a Array
type Array struct {
	Value            []*Any `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Array) Reset()                    { *m = Array{} }
func (m *Array) String() string            { return proto1.CompactTextString(m) }
func (*Array) ProtoMessage()               {}
func (*Array) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *Array) GetValue() []*Any {
	if m != nil {
		return m.Value
	}
	return nil
}

// a helper to allow all field types
type Any struct {
	Type             *Any_Type `protobuf:"varint,1,req,name=type,enum=Mysqlx.Datatypes.Any_Type" json:"type,omitempty"`
	Scalar           *Scalar   `protobuf:"bytes,2,opt,name=scalar" json:"scalar,omitempty"`
	Obj              *Object   `protobuf:"bytes,3,opt,name=obj" json:"obj,omitempty"`
	Array            *Array    `protobuf:"bytes,4,opt,name=array" json:"array,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Any) Reset()                    { *m = Any{} }
func (m *Any) String() string            { return proto1.CompactTextString(m) }
func (*Any) ProtoMessage()               {}
func (*Any) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *Any) GetType() Any_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Any_SCALAR
}

func (m *Any) GetScalar() *Scalar {
	if m != nil {
		return m.Scalar
	}
	return nil
}

func (m *Any) GetObj() *Object {
	if m != nil {
		return m.Obj
	}
	return nil
}

func (m *Any) GetArray() *Array {
	if m != nil {
		return m.Array
	}
	return nil
}

func init() {
	proto1.RegisterType((*Scalar)(nil), "Mysqlx.Datatypes.Scalar")
	proto1.RegisterType((*Scalar_String)(nil), "Mysqlx.Datatypes.Scalar.String")
	proto1.RegisterType((*Scalar_Octets)(nil), "Mysqlx.Datatypes.Scalar.Octets")
	proto1.RegisterType((*Object)(nil), "Mysqlx.Datatypes.Object")
	proto1.RegisterType((*Object_ObjectField)(nil), "Mysqlx.Datatypes.Object.ObjectField")
	proto1.RegisterType((*Array)(nil), "Mysqlx.Datatypes.Array")
	proto1.RegisterType((*Any)(nil), "Mysqlx.Datatypes.Any")
	proto1.RegisterEnum("Mysqlx.Datatypes.Scalar_Type", Scalar_Type_name, Scalar_Type_value)
	proto1.RegisterEnum("Mysqlx.Datatypes.Any_Type", Any_Type_name, Any_Type_value)
}

func init() { proto1.RegisterFile("mysqlx_datatypes.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x93, 0xdf, 0x6e, 0xda, 0x30,
	0x14, 0xc6, 0x95, 0xbf, 0xc0, 0x09, 0x65, 0x99, 0xd5, 0x75, 0x11, 0xda, 0xb4, 0x08, 0xb5, 0x93,
	0xb7, 0xa9, 0x91, 0xca, 0x13, 0x2c, 0x50, 0x3a, 0x75, 0xca, 0x88, 0x44, 0x02, 0xd2, 0x76, 0x63,
	0x85, 0x10, 0x2a, 0x58, 0x88, 0x19, 0x31, 0x51, 0x73, 0xb1, 0xd7, 0xdb, 0x0b, 0xec, 0x85, 0xa6,
	0xd8, 0x54, 0xed, 0x5a, 0x50, 0xaf, 0xf2, 0xf9, 0xe4, 0x67, 0x1f, 0x9f, 0xf3, 0x1d, 0xc3, 0xc9,
	0xaa, 0xcc, 0x7f, 0xa5, 0xb7, 0x64, 0x16, 0xb1, 0x88, 0x95, 0xeb, 0x24, 0x77, 0xd6, 0x1b, 0xca,
	0x28, 0x32, 0xbf, 0xf1, 0xb8, 0x73, 0x79, 0x17, 0xef, 0xfc, 0x51, 0x40, 0x0f, 0xe2, 0x28, 0x8d,
	0x36, 0xe8, 0x13, 0xa8, 0x55, 0xcc, 0x92, 0x6c, 0x19, 0xb7, 0xba, 0x6f, 0x9d, 0xc7, 0xac, 0x23,
	0x38, 0x27, 0x2c, 0xd7, 0x09, 0x3a, 0x86, 0x66, 0x41, 0xf2, 0xc5, 0x4d, 0x96, 0xcc, 0xc8, 0x22,
	0x63, 0x96, 0x6c, 0x4b, 0x18, 0xa1, 0x13, 0x68, 0x15, 0x64, 0x9b, 0x3d, 0x88, 0x2b, 0xb6, 0x84,
	0x55, 0x74, 0x01, 0xf5, 0x82, 0xd0, 0x98, 0x25, 0x2c, 0xb7, 0x34, 0x5b, 0xc2, 0x46, 0xf7, 0xdd,
	0xc1, 0xe3, 0x7d, 0x8e, 0x21, 0xb3, 0xda, 0x32, 0xa3, 0xdb, 0x69, 0x9a, 0x58, 0xba, 0x2d, 0x61,
	0x09, 0xbd, 0x80, 0x5a, 0x41, 0xe6, 0x29, 0x8d, 0x98, 0x55, 0xb3, 0x25, 0x2c, 0xa3, 0x16, 0xe8,
	0x05, 0x99, 0x52, 0x9a, 0x5a, 0x75, 0x5b, 0xc2, 0x75, 0x91, 0x25, 0x67, 0x9b, 0x45, 0x76, 0x63,
	0x35, 0x9e, 0xc9, 0x12, 0x70, 0xac, 0xfd, 0x11, 0x74, 0xa1, 0xd0, 0x11, 0x68, 0x45, 0x94, 0x6e,
	0x45, 0xf9, 0x4d, 0xf4, 0x12, 0x1a, 0x31, 0x4d, 0xd3, 0x88, 0x2d, 0x68, 0xc6, 0x8b, 0x53, 0xdb,
	0xe7, 0xa0, 0xef, 0xee, 0xf6, 0x88, 0x3d, 0x86, 0x66, 0x4c, 0x33, 0x96, 0x64, 0x8c, 0xf0, 0x06,
	0x56, 0xf8, 0x51, 0x67, 0x05, 0x2a, 0xef, 0x14, 0x80, 0x3e, 0x21, 0xc1, 0xf5, 0x30, 0x34, 0x25,
	0xa1, 0xc7, 0x95, 0x96, 0x85, 0x1e, 0x8e, 0x3d, 0xcf, 0x54, 0x50, 0x13, 0xea, 0x13, 0xe2, 0xf7,
	0xc3, 0x41, 0x18, 0x98, 0xaa, 0x58, 0x5d, 0xfa, 0xe3, 0x9e, 0x37, 0x30, 0x35, 0x64, 0x40, 0x6d,
	0x42, 0xae, 0x3c, 0xdf, 0x0d, 0x4d, 0x5d, 0x6c, 0xea, 0xf9, 0xbe, 0x67, 0xd6, 0x04, 0x16, 0x84,
	0xa3, 0xeb, 0xe1, 0x17, 0xb3, 0xde, 0xf9, 0x0d, 0xba, 0x3f, 0x5d, 0x26, 0x31, 0x43, 0x17, 0xa0,
	0xcc, 0xd3, 0x99, 0x25, 0xd9, 0x0a, 0x36, 0xba, 0xa7, 0x4f, 0x3b, 0x20, 0xb0, 0xdd, 0xe7, 0x6a,
	0x91, 0xa4, 0xb3, 0xf6, 0x67, 0x30, 0x1e, 0x2c, 0x91, 0x01, 0xca, 0xcf, 0xa4, 0xe4, 0xd5, 0x35,
	0xd0, 0xe9, 0x5d, 0xb1, 0xb2, 0x2d, 0x63, 0xa3, 0xfb, 0xea, 0xe9, 0x81, 0x6e, 0x56, 0x76, 0xce,
	0x41, 0x73, 0x37, 0x9b, 0xa8, 0xbc, 0xc7, 0x45, 0xfe, 0x03, 0xf8, 0x5f, 0x09, 0x14, 0x37, 0x2b,
	0x11, 0xfe, 0x6f, 0xe6, 0xda, 0x7b, 0x61, 0x31, 0x70, 0x18, 0xf4, 0x9c, 0x5b, 0xc7, 0xdb, 0x6b,
	0x74, 0xad, 0x43, 0xd6, 0xa2, 0x33, 0x50, 0xe8, 0x74, 0xc9, 0x27, 0x6f, 0x2f, 0xb6, 0x6b, 0xd3,
	0x7b, 0xd0, 0xa2, 0xea, 0xc6, 0x96, 0xca, 0xc1, 0xd7, 0x7b, 0x72, 0x57, 0xbf, 0x3b, 0x1f, 0xee,
	0x7d, 0x0c, 0xfa, 0xae, 0xe7, 0x8e, 0x84, 0x8f, 0x7e, 0xef, 0xeb, 0xa0, 0x5f, 0xf9, 0xd8, 0x00,
	0xcd, 0x1d, 0x8d, 0xdc, 0xef, 0xa6, 0xd2, 0x3b, 0x83, 0x37, 0x31, 0x5d, 0x39, 0xfc, 0xf1, 0x39,
	0xf1, 0x52, 0x88, 0x5b, 0xf1, 0xf6, 0xa6, 0xdb, 0xf9, 0x0f, 0x8d, 0xab, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xf0, 0xbd, 0xa3, 0xfe, 0x9e, 0x03, 0x00, 0x00,
}
